pcap4j:
  extension:
    util:
      tsharkPath: E:\Program Files\Wireshark\tshark.exe

honeyeye:
  system:
    inputingMode: 2 # 1:capture, 2:load
    outputingMode: 0 # 0:plugin, 1:transmission, 2:storage, 3: transmission and storage
  inputer:
    capturer:
      count: -1
      readTimeout: 60
      snaplen: 65536
      filter: tcp port 80 and (dst 192.168.31.137 or src 192.168.31.137)
      enableAutoFind: false
      enableNifParameter: true # true:parameter, false:console
      nifIndex: 3
      interval: 2
      logMode: 1 # 0: all, 1: parsed, 2: none
    loader:
      filePath: E:\Desktop\run1_3rtu_2s.pcap
  listener:
    meetingTimeout: 100  # in [s]
    segmentMax: 10000
    pluginGrain: 3 # 0:rawPacket, 1:packet, 2:flow, 3:session
    pluginTimeout: 100  # in [s]
    outputtingGrain: 3 # 0:rawPacket, 1:packet, 2:flow, 3:session
    outputtingTimeout: 0.2  # in [s]
    transmittingGrain: 1 # 0:rawPacket, 1:packet, 2:flow, 3:session
    transmittingTimeout: 1  # in [s]
    transmittingListener:
      port: 5150
      netAddress:  192.168.0.3
  outputer:
    filePath: E:\Desktop
    fileName: hellotest2